[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "python manage.py migrate --no-input && python manage.py loaddata wp_products"
startCommand = "gunicorn config.wsgi --workers 2 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"
