# Generated by Django 6.0.6 on 2026-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(upload_to='downloads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='downloads/thumbnails/')),
                ('category', models.CharField(choices=[('catalogue', 'Catalogue'), ('brochure', 'Brochure'), ('technical_sheet', 'Technical Sheet'), ('other', 'Other')], default='catalogue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
