# Generated by Django 6.0.6 on 2026-06-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a general/all-brand download', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='products.brand'),
        ),
        migrations.AddField(
            model_name='download',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
