# Generated by Django 6.0.6 on 2026-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='catalogue',
            field=models.FileField(blank=True, help_text='Upload brand catalogue PDF', null=True, upload_to='brands/catalogues/'),
        ),
    ]
